DROP ALL OBJECTS;

create table if not exists mpa_type(
    rating_mpa_id long generated by default as identity primary key,
    name varchar(40)

);

create table if not exists films(
    film_id long generated by default as identity primary key,
    name varchar(100) not null,
    description varchar(200) not null,
    release_date timestamp not null,
    duration long not null,
    rating_mpa_id int references mpa_type(rating_mpa_id)
);

create table if not exists users(
    user_id long generated by default as identity primary key,
    email varchar(50) not null,
    login varchar(50) not null,
    name varchar(50),
    birthday date not null
);

create table if not exists likes(
    like_id long generated by default as identity primary key,
    film_id long not null references films(film_id),
    user_id long not null references users(user_id)
);

create table if not exists genre_type(
    genre_id long generated by default as identity primary key,
    name varchar(40) not null
);

create table if not exists genre(
    id long generated by default as identity primary key,
    film_id long not null references films(film_id),
    genre_id long not null references genre_type(genre_id)
);

create table if not exists friends(
    relationship_id long generated by default as identity primary key,
    user_id long not null references users(user_id),
    friend_id long not null references users(user_id)
);